---
- name: Install useful gems
  become: true
  become_method: sudo
  gem:
    name: "{{ item.name }}"
    state: "{{ item.state|default('present') }}"
    user_install: "{{ item.install_only_for_user|default('no') }}"
  with_items: "{{ ruby_gemlist|default('[]') }}"
...
