---
- name: Install ruby tools
  become: true
  become_method: sudo
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - ruby
    - rubygem-rdoc
    - ruby-devel
    - rubygems
...
